# Generated by Django 5.2.5 on 2025-10-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=150)),
                ("company", models.CharField(max_length=150)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "technologies",
                    models.CharField(
                        help_text="Через кому: Django, React, PostgreSQL",
                        max_length=300,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                ("github_url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["-date", "title"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "level",
                    models.PositiveSmallIntegerField(default=50, help_text="0-100"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("backend", "Backend"),
                            ("frontend", "Frontend"),
                            ("tooling", "Tooling/DevOps"),
                            ("soft", "Soft"),
                        ],
                        default="soft",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "ordering": ["-level", "name"],
            },
        ),
    ]
