# Generated by Django 5.2.5 on 2025-11-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Ім’я клієнта"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("project_description", models.TextField(verbose_name="Опис проекту")),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Бюджет (USD)"
                    ),
                ),
                (
                    "deadline",
                    models.CharField(max_length=100, verbose_name="Терміни реалізації"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Нове замовлення"),
                            ("in_progress", "В обробці"),
                            ("done", "Завершено"),
                            ("rejected", "Відхилено"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
