# Generated by Django 5.2.5 on 2025-11-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="title",
            new_name="name",
        ),
    ]
