# Generated by Django 5.2.5 on 2025-11-06 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_rename_title_order_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
